[core]
xwayland=true
#shell=kiosk-shell.so

[shell]
panel-position=none

[launcher]
icon=/usr/share/weston/terminal.png
path=/usr/bin/weston-terminal

[output]
name=DSI-1
mode=320x480@60
transform=rotate-90
scale=0.5
